import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { DataTableStoreProvider } from "@/stores/dataTableStoreProvider";
import Script from "next/script";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <html lang="en">
                <body className={inter.className}>
                    <SessionProvider>
                        <TooltipProvider>
                            <DataTableStoreProvider isSelecting={false}>{children}</DataTableStoreProvider>
                            <Toaster />
                        </TooltipProvider>
                    </SessionProvider>
                </body>
            </html>
            <Script src="https://checkout.razorpay.com/v2/checkout.js" />
        </>
    );
}
